Cronograma
DevFestBolivia/devfest-mobile pull request #2
Opened 2022-10-21 02:30 UTC by armandohackcode

-  modificaciones en el archivo routes
-  modificaciones en el achivo main
-  añadido card cronograma
-  añadido cronograma screen
-  fix #1

2022-10-23 22:26 UTC, DentVega commented
please delete the changes in firebase files

direct the pull request to the develop branch

2022-10-24 02:13 UTC, irvin373 requested changes

2022-10-24 02:13 UTC, irvin373 commented on android/gradle.properties
> +org.gradle.java.home=/usr/lib/jvm/java-1.17.0-openjdk-amd64
are you sure about this line? set java home on a specific version

2022-10-24 02:13 UTC, irvin373 commented on lib/screens/cronograma_screen.dart
> +                return const CardCronograma();
I think is cleaner: `return const CardCronograma(interval: index == 3);`

2022-10-24 20:13 UTC, closed without merging